//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		schemas.opengis.net/kml/2.2.0/atom-author-link.xsd
package go_AtomAuthorLink

//	There is no official atom XSD. This XSD is created based on:
//	http://atompub.org/2005/08/17/atom.rnc. A subset of Atom as used in the
//	ogckml22.xsd is defined here.

import (
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasElem_Name struct {
	Name xsdt.String `xml:"http://www.w3.org/2005/Atom name"`
}

//	If the WalkHandlers.XsdGoPkgHasElem_Name function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElem_Name instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 0/1 field(s) belonging to this XsdGoPkgHasElem_Name instance.
func (me *XsdGoPkgHasElem_Name) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElem_Name
	if fn != nil {
		fn(me, true)
	}
	if fn != nil {
		fn(me, false)
	}
}

type XsdGoPkgHasElems_Name struct {
	Names []xsdt.String `xml:"http://www.w3.org/2005/Atom name"`
}

//	If the WalkHandlers.XsdGoPkgHasElems_Name function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElems_Name instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 0/1 field(s) belonging to this XsdGoPkgHasElems_Name instance.
func (me *XsdGoPkgHasElems_Name) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElems_Name
	if fn != nil {
		fn(me, true)
	}
	if fn != nil {
		fn(me, false)
	}
}

type XsdGoPkgHasElems_Uri struct {
	Uris []xsdt.String `xml:"http://www.w3.org/2005/Atom uri"`
}

//	If the WalkHandlers.XsdGoPkgHasElems_Uri function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElems_Uri instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 0/1 field(s) belonging to this XsdGoPkgHasElems_Uri instance.
func (me *XsdGoPkgHasElems_Uri) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElems_Uri
	if fn != nil {
		fn(me, true)
	}
	if fn != nil {
		fn(me, false)
	}
}

type XsdGoPkgHasElem_Uri struct {
	Uri xsdt.String `xml:"http://www.w3.org/2005/Atom uri"`
}

//	If the WalkHandlers.XsdGoPkgHasElem_Uri function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElem_Uri instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 0/1 field(s) belonging to this XsdGoPkgHasElem_Uri instance.
func (me *XsdGoPkgHasElem_Uri) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElem_Uri
	if fn != nil {
		fn(me, true)
	}
	if fn != nil {
		fn(me, false)
	}
}

type TatomEmailAddress xsdt.String

//	This convenience method just performs a simple type conversion to TatomEmailAddress's alias type xsdt.String.
func (me TatomEmailAddress) ToXsdtString() xsdt.String { return xsdt.String(me) }

//	Since TatomEmailAddress is just a simple String type, this merely sets the current value from the specified string.
func (me *TatomEmailAddress) SetFromString(s string) { (*xsdt.String)(me).SetFromString(s) }

//	Since TatomEmailAddress is just a simple String type, this merely returns the current string value.
func (me TatomEmailAddress) String() string { return xsdt.String(me).String() }

type XsdGoPkgHasElem_Email struct {
	Email TatomEmailAddress `xml:"http://www.w3.org/2005/Atom email"`
}

//	If the WalkHandlers.XsdGoPkgHasElem_Email function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElem_Email instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 0/1 field(s) belonging to this XsdGoPkgHasElem_Email instance.
func (me *XsdGoPkgHasElem_Email) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElem_Email
	if fn != nil {
		fn(me, true)
	}
	if fn != nil {
		fn(me, false)
	}
}

type XsdGoPkgHasElems_Email struct {
	Emails []TatomEmailAddress `xml:"http://www.w3.org/2005/Atom email"`
}

//	If the WalkHandlers.XsdGoPkgHasElems_Email function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElems_Email instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 0/1 field(s) belonging to this XsdGoPkgHasElems_Email instance.
func (me *XsdGoPkgHasElems_Email) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElems_Email
	if fn != nil {
		fn(me, true)
	}
	if fn != nil {
		fn(me, false)
	}
}

type TatomPersonConstruct struct {
	XsdGoPkgHasElems_Uri

	XsdGoPkgHasElems_Email

	XsdGoPkgHasElems_Name
}

//	If the WalkHandlers.TatomPersonConstruct function is not nil (ie. was set by outside code), calls it with this TatomPersonConstruct instance as the single argument. Then calls the Walk() method on 3/3 embed(s) and 0/0 field(s) belonging to this TatomPersonConstruct instance.
func (me *TatomPersonConstruct) Walk() {
	fn := WalkHandlers.TatomPersonConstruct
	if fn != nil {
		fn(me, true)
	}
	me.XsdGoPkgHasElems_Uri.Walk()
	me.XsdGoPkgHasElems_Email.Walk()
	me.XsdGoPkgHasElems_Name.Walk()
	if fn != nil {
		fn(me, false)
	}
}

type XsdGoPkgHasElem_Author struct {
	Author *TatomPersonConstruct `xml:"http://www.w3.org/2005/Atom author"`
}

//	If the WalkHandlers.XsdGoPkgHasElem_Author function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElem_Author instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 1/1 field(s) belonging to this XsdGoPkgHasElem_Author instance.
func (me *XsdGoPkgHasElem_Author) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElem_Author
	if fn != nil {
		fn(me, true)
	}
	me.Author.Walk()
	if fn != nil {
		fn(me, false)
	}
}

type XsdGoPkgHasElems_Author struct {
	Authors []*TatomPersonConstruct `xml:"http://www.w3.org/2005/Atom author"`
}

//	If the WalkHandlers.XsdGoPkgHasElems_Author function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElems_Author instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 0/1 field(s) belonging to this XsdGoPkgHasElems_Author instance.
func (me *XsdGoPkgHasElems_Author) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElems_Author
	if fn != nil {
		fn(me, true)
	}
	for _, x := range me.Authors {
		x.Walk()
	}
	if fn != nil {
		fn(me, false)
	}
}

type XsdGoPkgHasAttr_Title_XsdtString_ struct {
	Title xsdt.String `xml:"http://www.w3.org/2005/Atom title,attr"`
}

type XsdGoPkgHasAttr_Length_XsdtString_ struct {
	Length xsdt.String `xml:"http://www.w3.org/2005/Atom length,attr"`
}

type TatomLanguageTag xsdt.String

//	Since TatomLanguageTag is just a simple String type, this merely sets the current value from the specified string.
func (me *TatomLanguageTag) SetFromString(s string) { (*xsdt.String)(me).SetFromString(s) }

//	This convenience method just performs a simple type conversion to TatomLanguageTag's alias type xsdt.String.
func (me TatomLanguageTag) ToXsdtString() xsdt.String { return xsdt.String(me) }

//	Since TatomLanguageTag is just a simple String type, this merely returns the current string value.
func (me TatomLanguageTag) String() string { return xsdt.String(me).String() }

type XsdGoPkgHasAttr_Hreflang_TatomLanguageTag_ struct {
	Hreflang TatomLanguageTag `xml:"http://www.w3.org/2005/Atom hreflang,attr"`
}

type XsdGoPkgHasAttr_Rel_XsdtString_ struct {
	Rel xsdt.String `xml:"http://www.w3.org/2005/Atom rel,attr"`
}

type TatomMediaType xsdt.String

//	Since TatomMediaType is just a simple String type, this merely returns the current string value.
func (me TatomMediaType) String() string { return xsdt.String(me).String() }

//	Since TatomMediaType is just a simple String type, this merely sets the current value from the specified string.
func (me *TatomMediaType) SetFromString(s string) { (*xsdt.String)(me).SetFromString(s) }

//	This convenience method just performs a simple type conversion to TatomMediaType's alias type xsdt.String.
func (me TatomMediaType) ToXsdtString() xsdt.String { return xsdt.String(me) }

type XsdGoPkgHasAttr_Type_TatomMediaType_ struct {
	Type TatomMediaType `xml:"http://www.w3.org/2005/Atom type,attr"`
}

type XsdGoPkgHasAttr_Href_XsdtString_ struct {
	Href xsdt.String `xml:"http://www.w3.org/2005/Atom href,attr"`
}

type TxsdLink struct {
	XsdGoPkgHasAttr_Hreflang_TatomLanguageTag_

	XsdGoPkgHasAttr_Rel_XsdtString_

	XsdGoPkgHasAttr_Type_TatomMediaType_

	XsdGoPkgHasAttr_Href_XsdtString_

	XsdGoPkgHasAttr_Title_XsdtString_

	XsdGoPkgHasAttr_Length_XsdtString_
}

//	If the WalkHandlers.TxsdLink function is not nil (ie. was set by outside code), calls it with this TxsdLink instance as the single argument. Then calls the Walk() method on 0/6 embed(s) and 0/0 field(s) belonging to this TxsdLink instance.
func (me *TxsdLink) Walk() {
	fn := WalkHandlers.TxsdLink
	if fn != nil {
		fn(me, true)
	}
	if fn != nil {
		fn(me, false)
	}
}

type XsdGoPkgHasElems_Link struct {
	Links []*TxsdLink `xml:"http://www.w3.org/2005/Atom link"`
}

//	If the WalkHandlers.XsdGoPkgHasElems_Link function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElems_Link instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 0/1 field(s) belonging to this XsdGoPkgHasElems_Link instance.
func (me *XsdGoPkgHasElems_Link) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElems_Link
	if fn != nil {
		fn(me, true)
	}
	for _, x := range me.Links {
		x.Walk()
	}
	if fn != nil {
		fn(me, false)
	}
}

type XsdGoPkgHasElem_Link struct {
	Link *TxsdLink `xml:"http://www.w3.org/2005/Atom link"`
}

//	If the WalkHandlers.XsdGoPkgHasElem_Link function is not nil (ie. was set by outside code), calls it with this XsdGoPkgHasElem_Link instance as the single argument. Then calls the Walk() method on 0/0 embed(s) and 1/1 field(s) belonging to this XsdGoPkgHasElem_Link instance.
func (me *XsdGoPkgHasElem_Link) Walk() {
	fn := WalkHandlers.XsdGoPkgHasElem_Link
	if fn != nil {
		fn(me, true)
	}
	me.Link.Walk()
	if fn != nil {
		fn(me, false)
	}
}

//	Provides 12 strong-typed hooks for your own custom handler functions to be invoked when the Walk() method is called on any instance of any (non-attribute-related) struct type defined in this package.
//	If your custom handler does get called at all for a given struct instance, then it always gets called twice, first with the 'enter' bool argument set to true, then (after having Walk()ed all subordinate struct instances, if any) once again with it set to false.
var WalkHandlers = &XsdGoPkgWalkHandlers{}

//	Provides 12 strong-typed hooks for your own custom handler functions to be invoked when the Walk() method is called on any instance of any (non-attribute-related) struct type defined in this package.
//	If your custom handler does get called at all for a given struct instance, then it always gets called twice, first with the 'enter' bool argument set to true, then (after having Walk()ed all subordinate struct instances, if any) once again with it set to false.
type XsdGoPkgWalkHandlers struct {
	XsdGoPkgHasElem_Name    func(o *XsdGoPkgHasElem_Name, enter bool)
	TatomPersonConstruct    func(o *TatomPersonConstruct, enter bool)
	XsdGoPkgHasElems_Name   func(o *XsdGoPkgHasElems_Name, enter bool)
	XsdGoPkgHasElem_Author  func(o *XsdGoPkgHasElem_Author, enter bool)
	XsdGoPkgHasElem_Uri     func(o *XsdGoPkgHasElem_Uri, enter bool)
	XsdGoPkgHasElems_Uri    func(o *XsdGoPkgHasElems_Uri, enter bool)
	XsdGoPkgHasElem_Email   func(o *XsdGoPkgHasElem_Email, enter bool)
	XsdGoPkgHasElems_Author func(o *XsdGoPkgHasElems_Author, enter bool)
	TxsdLink                func(o *TxsdLink, enter bool)
	XsdGoPkgHasElems_Link   func(o *XsdGoPkgHasElems_Link, enter bool)
	XsdGoPkgHasElem_Link    func(o *XsdGoPkgHasElem_Link, enter bool)
	XsdGoPkgHasElems_Email  func(o *XsdGoPkgHasElems_Email, enter bool)
}
