//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		kbcafe.com/rss/atom.xsd.xml
package gopkg_KbcafeComRssAtomXsdXml

//	This version of the Atom schema is based on version 1.0 of the format specifications,
//	found here http://www.atomenabled.org/developers/syndication/atom-format-spec.php.
//	An Atom document may have two root elements, feed and entry, as defined in section 2.


import (
	xml "github.com/metaleap/go-xsd-pkg/www.w3.org/2001/03/xml.xsd_go"
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasAtts_CommonAttributes struct {
	xml.XsdGoPkgHasAttr_Lang

	xml.XsdGoPkgHasAttr_Base

}

//	The Atom feed construct is defined in section 4.1.1 of the format spec.
//	The Atom text construct is defined in section 3.1 of the format spec.
type XsdGoPkgHasCdata struct {
	XsdGoPkgCDATA string `xml:",chardata"`

}

type TxsdTextTypeType xsdt.Token

//	Returns true if the value of this enumerated TxsdTextTypeType is "html".
func (me TxsdTextTypeType) IsHtml () bool { return me == "html" }

//	Since TxsdTextTypeType is just a simple String type, this merely sets the current value from the specified string.
func (me *TxsdTextTypeType) SetFromString (s string)  { (*xsdt.Token)(me).SetFromString(s) }

//	Since TxsdTextTypeType is just a simple String type, this merely returns the current string value.
func (me TxsdTextTypeType) String () string { return xsdt.Token(me).String() }

//	Returns true if the value of this enumerated TxsdTextTypeType is "xhtml".
func (me TxsdTextTypeType) IsXhtml () bool { return me == "xhtml" }

//	This convenience method just performs a simple type conversion to TxsdTextTypeType's alias type xsdt.Token.
func (me TxsdTextTypeType) ToXsdtToken () xsdt.Token { return xsdt.Token(me) }

//	Returns true if the value of this enumerated TxsdTextTypeType is "text".
func (me TxsdTextTypeType) IsText () bool { return me == "text" }

type XsdGoPkgHasAttr_Type_TxsdTextTypeType_ struct {
	Type TxsdTextTypeType `xml:"http://www.w3.org/2005/Atom type,attr"`

}

type TtextType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasAttr_Type_TxsdTextTypeType_

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_rightschoicefeedTypeschema_Rights_TtextType_ struct {
	Rightses []*TtextType `xml:"http://www.w3.org/2005/Atom rights"`

}

//	The Atom person construct is defined in section 3.2 of the format spec.
type XsdGoPkgHasElems_namechoicepersonTypeschema_Name_XsdtString_ struct {
	Names []xsdt.String `xml:"http://www.w3.org/2005/Atom name"`

}

//	Schema definition for an email address.
type TemailType xsdt.NormalizedString

//	Since TemailType is just a simple String type, this merely returns the current string value.
func (me TemailType) String () string { return xsdt.NormalizedString(me).String() }

//	Since TemailType is just a simple String type, this merely sets the current value from the specified string.
func (me *TemailType) SetFromString (s string)  { (*xsdt.NormalizedString)(me).SetFromString(s) }

//	This convenience method just performs a simple type conversion to TemailType's alias type xsdt.NormalizedString.
func (me TemailType) ToXsdtNormalizedString () xsdt.NormalizedString { return xsdt.NormalizedString(me) }

type XsdGoPkgHasElems_emailchoicepersonTypeschema_Email_TemailType_ struct {
	Emails []TemailType `xml:"http://www.w3.org/2005/Atom email"`

}

type TuriType struct {
	XsdGoPkgValue xsdt.AnyURI `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_urichoicepersonTypeschema_Uri_TuriType_ struct {
	Uris []*TuriType `xml:"http://www.w3.org/2005/Atom uri"`

}

type TpersonType struct {
	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasElems_urichoicepersonTypeschema_Uri_TuriType_

	XsdGoPkgHasElems_namechoicepersonTypeschema_Name_XsdtString_

	XsdGoPkgHasElems_emailchoicepersonTypeschema_Email_TemailType_

}

type XsdGoPkgHasElems_authorchoicefeedTypeschema_Author_TpersonType_ struct {
	Authors []*TpersonType `xml:"http://www.w3.org/2005/Atom author"`

}

//	The Atom cagegory construct is defined in section 4.2.2 of the format spec.
type XsdGoPkgHasAttr_Label_XsdtString_ struct {
	Label xsdt.String `xml:"http://www.w3.org/2005/Atom label,attr"`

}

type XsdGoPkgHasAttr_Scheme_XsdtAnyURI_ struct {
	Scheme xsdt.AnyURI `xml:"http://www.w3.org/2005/Atom scheme,attr"`

}

type XsdGoPkgHasAttr_Term_XsdtString_ struct {
	Term xsdt.String `xml:"http://www.w3.org/2005/Atom term,attr"`

}

type TcategoryType struct {
	XsdGoPkgHasAttr_Scheme_XsdtAnyURI_

	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasAttr_Term_XsdtString_

	XsdGoPkgHasAttr_Label_XsdtString_

}

type XsdGoPkgHasElems_categorychoicefeedTypeschema_Category_TcategoryType_ struct {
	Categories []*TcategoryType `xml:"http://www.w3.org/2005/Atom category"`

}

//	The Atom entry construct is defined in section 4.1.2 of the format spec.
//	The Atom content construct is defined in section 4.1.3 of the format spec.
type XsdGoPkgHasAttr_Src_XsdtAnyURI_ struct {
	Src xsdt.AnyURI `xml:"http://www.w3.org/2005/Atom src,attr"`

}

type XsdGoPkgHasAttr_Type_XsdtString_ struct {
	Type xsdt.String `xml:"http://www.w3.org/2005/Atom type,attr"`

}

type TcontentType struct {
	XsdGoPkgHasAttr_Src_XsdtAnyURI_

	XsdGoPkgHasAttr_Type_XsdtString_

	XsdGoPkgHasCdata

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_contentchoiceentryTypeschema_Content_TcontentType_ struct {
	Contents []*TcontentType `xml:"http://www.w3.org/2005/Atom content"`

}

//	The Atom link construct is defined in section 3.4 of the format spec.
type XsdGoPkgHasAttr_Title_XsdtString_ struct {
	Title xsdt.String `xml:"http://www.w3.org/2005/Atom title,attr"`

}

type XsdGoPkgHasAttr_Length_XsdtPositiveInteger_ struct {
	Length xsdt.PositiveInteger `xml:"http://www.w3.org/2005/Atom length,attr"`

}

type XsdGoPkgHasAttr_Href_XsdtAnyURI_ struct {
	Href xsdt.AnyURI `xml:"http://www.w3.org/2005/Atom href,attr"`

}

type XsdGoPkgHasAttr_Hreflang_XsdtNmtoken_ struct {
	Hreflang xsdt.Nmtoken `xml:"http://www.w3.org/2005/Atom hreflang,attr"`

}

type XsdGoPkgHasAttr_Rel_XsdtString_ struct {
	Rel xsdt.String `xml:"http://www.w3.org/2005/Atom rel,attr"`

}

type TlinkType struct {
	XsdGoPkgHasAttr_Title_XsdtString_

	XsdGoPkgHasAttr_Length_XsdtPositiveInteger_

	XsdGoPkgHasAttr_Href_XsdtAnyURI_

	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasCdata

	XsdGoPkgHasAttr_Hreflang_XsdtNmtoken_

	XsdGoPkgHasAttr_Rel_XsdtString_

}

type XsdGoPkgHasElems_linkchoiceentryTypeschema_Link_TlinkType_ struct {
	Links []*TlinkType `xml:"http://www.w3.org/2005/Atom link"`

}

type XsdGoPkgHasElems_sourcechoiceentryTypeschema_Source_TtextType_ struct {
	Sources []*TtextType `xml:"http://www.w3.org/2005/Atom source"`

}

type TdateTimeType struct {
	XsdGoPkgValue xsdt.DateTime `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_publishedchoiceentryTypeschema_Published_TdateTimeType_ struct {
	Publisheds []*TdateTimeType `xml:"http://www.w3.org/2005/Atom published"`

}

//	The Atom id construct is defined in section 4.2.6 of the format spec.
type TidType struct {
	XsdGoPkgValue xsdt.AnyURI `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_idchoiceentryTypeschema_Id_TidType_ struct {
	Ids []*TidType `xml:"http://www.w3.org/2005/Atom id"`

}

type XsdGoPkgHasElems_contributorchoiceentryTypeschema_Contributor_TpersonType_ struct {
	Contributors []*TpersonType `xml:"http://www.w3.org/2005/Atom contributor"`

}

type XsdGoPkgHasElems_titlechoiceentryTypeschema_Title_TtextType_ struct {
	Titles []*TtextType `xml:"http://www.w3.org/2005/Atom title"`

}

type XsdGoPkgHasElems_updatedchoiceentryTypeschema_Updated_TdateTimeType_ struct {
	Updateds []*TdateTimeType `xml:"http://www.w3.org/2005/Atom updated"`

}

type XsdGoPkgHasElems_summarychoiceentryTypeschema_Summary_TtextType_ struct {
	Summaries []*TtextType `xml:"http://www.w3.org/2005/Atom summary"`

}

type TentryType struct {
	XsdGoPkgHasElems_publishedchoiceentryTypeschema_Published_TdateTimeType_

	XsdGoPkgHasElems_rightschoicefeedTypeschema_Rights_TtextType_

	XsdGoPkgHasElems_idchoiceentryTypeschema_Id_TidType_

	XsdGoPkgHasElems_contributorchoiceentryTypeschema_Contributor_TpersonType_

	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasElems_titlechoiceentryTypeschema_Title_TtextType_

	XsdGoPkgHasElems_updatedchoiceentryTypeschema_Updated_TdateTimeType_

	XsdGoPkgHasElems_summarychoiceentryTypeschema_Summary_TtextType_

	XsdGoPkgHasElems_authorchoicefeedTypeschema_Author_TpersonType_

	XsdGoPkgHasElems_contentchoiceentryTypeschema_Content_TcontentType_

	XsdGoPkgHasElems_linkchoiceentryTypeschema_Link_TlinkType_

	XsdGoPkgHasElems_categorychoicefeedTypeschema_Category_TcategoryType_

	XsdGoPkgHasElems_sourcechoiceentryTypeschema_Source_TtextType_

}

type XsdGoPkgHasElems_entrychoicefeedTypeschema_Entry_TentryType_ struct {
	Entries []*TentryType `xml:"http://www.w3.org/2005/Atom entry"`

}

type XsdGoPkgHasElems_subtitlechoicefeedTypeschema_Subtitle_TtextType_ struct {
	Subtitles []*TtextType `xml:"http://www.w3.org/2005/Atom subtitle"`

}

//	The Atom logo construct is defined in section 4.2.8 of the format spec.
type TlogoType struct {
	XsdGoPkgValue xsdt.AnyURI `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_logochoicefeedTypeschema_Logo_TlogoType_ struct {
	Logos []*TlogoType `xml:"http://www.w3.org/2005/Atom logo"`

}

//	The Atom icon construct is defined in section 4.2.5 of the format spec.
type TiconType struct {
	XsdGoPkgValue xsdt.AnyURI `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_iconchoicefeedTypeschema_Icon_TiconType_ struct {
	Icons []*TiconType `xml:"http://www.w3.org/2005/Atom icon"`

}

//	The Atom generator element is defined in section 4.2.4 of the format spec.
type XsdGoPkgHasAttr_Version_XsdtString_ struct {
	Version xsdt.String `xml:"http://www.w3.org/2005/Atom version,attr"`

}

type XsdGoPkgHasAttr_Uri_XsdtAnyURI_ struct {
	Uri xsdt.AnyURI `xml:"http://www.w3.org/2005/Atom uri,attr"`

}

type TgeneratorType struct {
	XsdGoPkgValue xsdt.String `xml:",chardata"`

	XsdGoPkgHasAttr_Version_XsdtString_

	XsdGoPkgHasAttr_Uri_XsdtAnyURI_

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_generatorchoicefeedTypeschema_Generator_TgeneratorType_ struct {
	Generators []*TgeneratorType `xml:"http://www.w3.org/2005/Atom generator"`

}

type TfeedType struct {
	XsdGoPkgHasElems_rightschoicefeedTypeschema_Rights_TtextType_

	XsdGoPkgHasElems_authorchoicefeedTypeschema_Author_TpersonType_

	XsdGoPkgHasElems_categorychoicefeedTypeschema_Category_TcategoryType_

	XsdGoPkgHasElems_entrychoicefeedTypeschema_Entry_TentryType_

	XsdGoPkgHasElems_updatedchoiceentryTypeschema_Updated_TdateTimeType_

	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasElems_subtitlechoicefeedTypeschema_Subtitle_TtextType_

	XsdGoPkgHasElems_logochoicefeedTypeschema_Logo_TlogoType_

	XsdGoPkgHasElems_titlechoiceentryTypeschema_Title_TtextType_

	XsdGoPkgHasElems_iconchoicefeedTypeschema_Icon_TiconType_

	XsdGoPkgHasElems_contributorchoiceentryTypeschema_Contributor_TpersonType_

	XsdGoPkgHasElems_generatorchoicefeedTypeschema_Generator_TgeneratorType_

	XsdGoPkgHasElems_idchoiceentryTypeschema_Id_TidType_

	XsdGoPkgHasElems_linkchoiceentryTypeschema_Link_TlinkType_

}

type XsdGoPkgHasElem_Feed struct {
	Feed *TfeedType `xml:"http://www.w3.org/2005/Atom feed"`

}

type XsdGoPkgHasElems_Feed struct {
	Feeds []*TfeedType `xml:"http://www.w3.org/2005/Atom feed"`

}

type XsdGoPkgHasElem_Entry struct {
	Entry *TentryType `xml:"http://www.w3.org/2005/Atom entry"`

}
